# Generated by Django 3.0.4 on 2020-04-18 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0007_auto_20200415_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('poster', models.URLField(blank=True)),
                ('link', models.URLField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Security')),
            ],
        ),
    ]
