# Generated by Django 3.0.4 on 2020-04-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.URLField()),
                ('currency', models.CharField(max_length=3)),
                ('exchange', models.CharField(max_length=6)),
                ('stock', models.BooleanField()),
                ('price', models.FloatField()),
                ('_yield', models.FloatField()),
            ],
        ),
    ]
