# Generated by Django 3.0.4 on 2020-04-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
