# Generated by Django 3.0.4 on 2020-04-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_security_last_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security',
            old_name='_yield',
            new_name='yield_value',
        ),
    ]
