# Generated by Django 3.0.4 on 2020-04-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_auto_20200406_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security',
            old_name='yield_value',
            new_name='_yield',
        ),
    ]
