# Generated by Django 3.0.4 on 2020-04-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_auto_20200406_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='foreign',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
