# Generated by Django 3.0.4 on 2020-04-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_security_foreign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='ticker',
            field=models.CharField(max_length=25),
        ),
    ]
