# Generated by Django 3.0.4 on 2020-04-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_auto_20200415_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='_yield',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='security',
            name='exchange',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='security',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
