# Generated by Django 3.0.4 on 2020-04-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_auto_20200415_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='ticker',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
