# Generated by Django 3.0.4 on 2020-04-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_auto_20200422_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='isin',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
